<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="PrettyPrompt" Version="6.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../UIEngine.Framework/UIEngine.Framework.csproj" />
    <ProjectReference Include="../../Samples/UIEngine.Samples.CyclicDomain/UIEngine.Samples.CyclicDomain.csproj" />
  </ItemGroup>
</Project>
