namespace UIEngine.Core;

public enum InteractionErrorCode
{
    NONE = 0,
    INVALID_ROOT_IDENTIFIER = 1,
    DUPLICATE_ROOT_IDENTIFIER = 2,
    UNSUPPORTED_TARGET_TYPE = 3,
    TARGET_UNAVAILABLE = 4,
    DESCRIPTOR_UNAVAILABLE = 5,
    INVALID_INPUT = 6,
    CONVERSION_FAILED = 7,
    VALIDATION_FAILED = 8,
    INVOCATION_FAILED = 9,
    CANCELLED = 10,
    HOST_DISPOSED = 11,
    INVALID_DOMAIN_IDENTITY = 12,
    CONFLICTING_DOMAIN_IDENTITY = 13,
    DOMAIN_IDENTITY_NOT_FOUND = 14,
    AMBIGUOUS_DOMAIN_IDENTITY = 15,
    ROOT_NOT_FOUND = 16,
    IDENTITY_PROVIDER_FAILED = 17,
    INVALID_PATH = 18,
    TARGET_MISSING = 19,
    AMBIGUOUS_TARGET = 20,
    TYPE_MISMATCH = 21,
    PERMISSION_DENIED = 22,
    DISPATCH_FAILED = 23,
}
