namespace UIEngine.Core;

public enum InteractionErrorCode
{
    NONE = 0,
    INVALID_ROOT_IDENTIFIER = 1,
    DUPLICATE_ROOT_IDENTIFIER = 2,
    UNSUPPORTED_TARGET_TYPE = 3,
    TARGET_UNAVAILABLE = 4,
    DESCRIPTOR_UNAVAILABLE = 5,
    INVALID_INPUT = 6,
    CONVERSION_FAILED = 7,
    VALIDATION_FAILED = 8,
    INVOCATION_FAILED = 9,
    CANCELLED = 10,
}
