<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>UIEngine.Frontend.Tui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="XenoAtom.Terminal.UI" Version="3.9.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../Core/Core.csproj" />
  </ItemGroup>
</Project>
